# CARA SELEKSI PADA MYSQL
# SELEKSI SELURUH DATABASE SECARA LANGSUNG, "SELECT *" HASILNYA SEMUA DATABASE DAN TABLE DI DALAMNYA SEMUA TERSELEKSI

-- SELECT *
-- FROM employee_demographics;

# CARA PENULISAN DI ATAS BERPOTENSI ERROR JIKA BEKERJA DALAM JUMLAH DATABASE YANG BANYAK / DATABASE YANG DISELEKSI
# ARTINYA KITA MENSELEKSI TABLE DENGAN NAMA employee_demographics TANPA TAHU BERADA DI DATABASE YG MANA
# TITIK KOMA DI AKHIR BERFUNGSI UNTUK MEMBERI TAHU SQL KITA AKHIR DARI QUERY ATAU UNTUK MEMISAHKAN / MEMBEDAKAN 2 / LEBIH QUERY

# BEST PRACTICE PENULISAN ADALAH SBB :
SELECT *
FROM parks_and_recreation.employee_demographics;

# KITA DEKLARASI TERLEBIH DAHULU NAMA DATABASE SECARA SPESIFIK SEBELUM NAMA TABLE
# INI MENJELASKAN PADA MYSQL BAHWA TABLE PADA DATABASE YG SPESIFIK SAJA LAH YANG DI PILIH

-- ========================================================== --

# KITA BISA MENSELEKSI DATA SECARA SPESIFIK (TDK SELURUHNYA) DENGAN CARA SELEKSI NAMA COLUMN YANG INGIN DILIHAT

SELECT first_name
FROM parks_and_recreation.employee_demographics;

# SECARA RINGKAS KITA BISA MEMBACA SEPERTI INI :
# PILIH KOLOM first_name DARI DATABASE DENGAN NAMA parks_and_recreation PADA TABLE DGN NAMA employee_demographics;

-- ========================================================== --

-- MULTI SELECT --
# KITA JUGA BISA MENSELEKSI BEBERAPA KOLOM YG DINGINKAN SEKALIGUS, DENGAN CARA SBB :

SELECT
first_name,
gender,
birth_date,
age
FROM parks_and_recreation.employee_demographics;

# CARA PENULISAN DIATAS ADALAH CARA BEST PRACTICE YANG READABLE
# ARTINYA KITA SELEKSI KOLOM first_name, gender, dan birth_date DI DB parks_and_recreation DGN NAMA TABLE employee_demographics
# KITA JUGA BISA MENAMBAHKAN KOLOM SECARA LANGSUNG DENGAN PERINTAH SBB :

# KITA INGIN KOLOM FULLNAME YANG MENGGABUNGKAN first_name + last_name
SELECT 
first_name,
last_name,
age,
(age + 10) * 10 + 10 -- (coba bikin kolom baru)
FROM parks_and_recreation.employee_demographics;

# ADA TYPE KALKULASI, OPERASI MTK SELURUHNYA DI TERDAPAT DALAM ATURAN PEMDOSS (UTK OPERASI ARITMATIKA / MTK)
# PEMDAS 

-- ========================================================== --

-- DISTINCT --
# DISTINCT ADALAH METODE YANG MEMUNGKINKAN HANYA U/ MENSELEKSI NILAI YANG UNIK SAJA PADA KOLOM

SELECT DISTINCT gender
FROM parks_and_recreation.employee_demographics;

# JIKA DITEMUKAN DATA UNIK YANG SAMA MAKA AKAN DITAMPILKAN DATA YANG UNIK SAJA
# TAPI JIKA YANG DI SELEKSI DENGAN DISTINCT LEBIH DARI 1 DAN DI TEMUKAN SALAH SATU DATA ADA YANG UNIK, MAKA HASIL SEMUANYA AKAN MENJADI UNIK

SELECT DISTINCT first_name, gender
FROM parks_and_recreation.employee_demographics;


