-- WHERE CLAUSE

# PENGGUNAAN AND, OR, NOT
# DITULIS DENGAN CARA :
# SELECT * FROM [NAMA_TABLES] WHERE [NAMA_KOLOM] = "[VALUE]"

# CONTOH
SELECT *
FROM parks_and_recreation.employee_salary
WHERE first_name = "Ron"
;
# HASILNYA AKAN MENAMPILKAN BARIS DARI VALUE YANG SPESIFIK DI PILIH

# CONTOH COMPARISON
SELECT *
FROM parks_and_recreation.employee_salary
WHERE salary > 50000
;
# HASILNYA YG DI ATAS 50000 DITAMPILKAN DAN YG PAS 50000 TDK DITAMPILKAN

-- CONTOH LAIN
SELECT *
FROM parks_and_recreation.employee_salary
WHERE salary >= 50000
;
# HASILNYA YG DI ATAS 50000 DITAMPILKAN DAN PAS 50000 JUGA DITAMPILKAN

-- CONTOH LAIN
SELECT *
FROM parks_and_recreation.employee_salary
WHERE salary < 25000
;
# HASILNYA YG DI BAWAH 25000 DITAMPILKAN DAN PAS 25000 TIDAK DITAMPILKAN

SELECT *
FROM parks_and_recreation.employee_salary
WHERE salary <= 25000
;
# HASILNYA YG DI BAWAH 25000 DAN PAS 25000 DITAMPILKAN

-- CONTOH LAIN
SELECT DISTINCT first_name, salary
FROM parks_and_recreation.employee_salary
WHERE salary <= 25000
;

# CONTOH NOT EQUALS (KEBALIKAN)
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE gender != "Female"
;

-- CONTOH pada birth_date
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE birth_date > '1985-01-01'
;
# FORMAT TANGGAL INI MENGHASILKAN TAHUN YG LEBIH TERBARU YG DICARI JADI MENAMPILKAN TAHUN '1986, 1987'

# LOGICAL OPERATOR -- AND OR NOT

-- CONTOH PENGGUNAAN AND
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE birth_date > '1985-01-01'
AND gender = "male"
;
# HASILNYA HANYA MENAMPILKAN THN ULTAH YG LEBIH BESAR DAN HANYA GENDER MALE SAJA (HASILKAN DATA YG TRUE)

-- CONTOH PENGGUNAAN OR
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE birth_date > '1985-01-01'
OR gender = "male"
;
# HASILKAN DATA DENGAN PILIHAN KONDISI FALSE YG DI SEBABKAN KOLOM KEDUANYA
# UNTUK MENCARI YG LEBIH SPESIFIK KITA JUGA BISA TAMBAHKAN NOT

-- CONTOH LAIN
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE birth_date > '1985-01-01'
OR NOT gender = "male"
;
# HASILNYA BISA DIBACA SEBAGAI BERIKUT :
# DATA YANG TANGGAL ULTAHNYA DIATAS TGL TSB (TDK DITAMPILKAN) ATAU YANG BUKAN TERMASUK GENDER MALE (FEMALE) MESKIPUN TGL DIBAWAH TSB (TETAP DITAMPILKAN)

-- ISOLATED CONDITIONAL STATEMENT
# CONTOH (MENGGUNAKAN PARENTHESIS () )
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE (first_name = "April" AND age = 29) OR age <= 35
;
# YANG DI DALAM KURUNG DAN OR DILUARNYA MEMILIKI KONDISI YANG BERBEDA
# YANG DI DALAM KURUNG DI SEBUT ISOLATED CONDITIONAL STATEMENT
# BACANYA, JIKA YG DI ISOLATED BENAR MAKA TAMPILKAN, JIKA KONDISI DENGAN OR DILUARNYA BENAR TAMPILKAN

-- LIKE STATEMENT
# SEBUAH METODE SANGAT UNIQ U/ MELIHAT (MENAMPILKAN DATA) DARI PATTERN YANG BELUM PASTI (TDK SEMPURNA)
# CONTOH STATEMENT PENCARIAN SEMPURNA
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE first_name = "Jerry" -- ini sudah pasti tampil
;

# CONTOH STATEMENT PENCARIAN BLM SEMPURNA
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE first_name = "Jer" -- ini tidak tampil
;
-- MAKA KITA GUNAKAN LIKE U/ MENAMPILKAN DATA YANG MEMILIKI VALUE TERTENTU DI DALAMNYA
-- DENGAN PENAMBAHAN SPESIAL KARAKTER % DAN _ SETELAHNYA
-- % BERMAKNA APAPUN DAN _ BERMAKNA SPESIFIK VALUE
# CONTOH
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE first_name LIKE "Jer%" -- MENCARI JERRY (TAMPILKAN DATA APAPUN YANG MEMILIKI KARAKTER 'Jer' di kolom first_name
;

-- ATAU ADA PENULISAN DENGAN MENCARI NILAI DI TENGAHNYA

SELECT *
FROM parks_and_recreation.employee_demographics
WHERE first_name LIKE "%er%" -- MENCARI JERRY (TAMPILKAN APAPUN VALUE APAPUN YANG MEMILIKI KARAKTER 'er' di kolom first_name
;
# HASILNYA DATA YANG MENGANDUNG VALUE JER DAN KATA APAPUN SETELAHNYA AKAN TAMPIL

-- CONTOH LAIN MENERAPKAN __
-- UNDERSCORE MEWAKILIKI SPESIFIK JUMLAH KARAKTER YANG AKAN DI TAMPILKAN
-- MASUKKAN JUMLAH UNDERSCORE SESUAI DATA YANG INGIN DI TAMPILKAN

SELECT *
FROM parks_and_recreation.employee_demographics
WHERE first_name LIKE "_nn"
;
#HASILNYA MENAMPILKAN 1 KARAKTER DENGAN HURUF 'nn' SETELAHNYA

-- CONTOH LAIN
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE first_name LIKE 'A__%' -- MENAMPILKAN DATA DI KOLOM FIRST_NAME DENGAN KARAKTER AWAL A DIIKUTI 2 KARAKTER SETELAHNYA DAN KARAKTER APAPUN DIBELAKANGNYA
;

-- CONTOH PADA birth_date
SELECT *
FROM parks_and_recreation.employee_demographics
WHERE birth_date LIKE '1985%'
;









