-- GROUP BY & ORDER BY --
# GROUP BY U/ MENGGABUNGKAN BARIS YANG MEMILIKI NILAI YANG SAMA SECARA SPESIFIK PADA KOLUM YANG TELAH DIKELOMPOKKAN
# KETIKA GROUP BERJALAN, KAMU DAPAT MENJALANKAN SESUATU YANG DISEBUT DENGAT AGGREGATE FUNTION PADA BARISNYA

SELECT *
FROM parks_and_recreation.employee_demographics;

SELECT gender
FROM parks_and_recreation.employee_demographics
GROUP BY gender
;

# JIKA DITANYA APA PERBEDAANNYA DENGAN MENGGUNAKAN DISTINCT gender, MAKA JAWABANNYA ADALAH
# MENGGUNAKAN GROUP BY MEMUNGKINKAN KITA UNTUK MENGGUNAKAN AGGREGATE FUNCTIONS SEPERTI AVERAGE, MIN, MAX BERBASIS PADA ROWS YG TERSELEKSI
# apa bedanya dengan selct gender diatas ?
# JIKA LIST YANG DI SELEKSI BUKAN MENGGUNAKAN GROUP BY CLAUSE DAN MENGANDUNG NON AGREGATED COLUMNS, ARTINYA :
# KETIKA KITA MILIH KOLOM YANG TERSELEKSI ARTINYA KOLOM ITU BUKAN KOLOM AGREGATED YG BISA MENJALANKAN FUNGSI SEPERTI AVERAGE, MIN, MAX
# JIKA KITA TIDAK MENGGUNAKAN AGGREGATE FUNCTION PADA STATEMENT YANG DIPILIH SESUAI DENGAN GROUP BY NYA, MAKA HARUS COCOK (SAMA) ANTARA SELECT DAN GROUP BY

# CONTOH KITA INGIN MENCARI NILAI RATA - RATA PADA AGE (USIA) SESUAI GENDER
# CARANYA KITA SELECT gender GROUPING BY gender LALU TAMBAHKAN KOMA LALU TAMBAHKAN AGE()

SELECT gender, AVG(age), MAX(age), MIN(age), COUNT(age)
FROM parks_and_recreation.employee_demographics
GROUP BY gender
;

# INI BISA DIBACA SBB, PILIH & KELOMPOKAN KOLOM GENDER, LALU HITUNG RATA RATA NILAI DALAM KOLOM AGE

# CONTOH LAIN
# GROUPING KOLOM OCCUPATION DI TABLES EMPLOYEE SALARY
# TDK BISA MENGGUNAKAN DISTINCT YG AKAN MENGHASILKAN 2 NILAI (TDK BISA AGREGATE FUNCTION)
# DGN GROUPING DIA AKAN MENSORTIR NILAI YG UNIQ, SEHINGGA PD CONTOH DIA AKAN MENAMPILKAN 1 DATA saja DIANTARA 2 DATA YG SAMA 
# KECUALI JIKA MULTIPLE SELECTION 2 KOLOM YG DIBANDINGKAN MEMILIKI NILAI YG BEDA MAKA TETAP DI TAMPILKAN SEPERTI ATURAN DISTINCT
# PADA GROUPING JUGA BISA MULTIPLE SELECTION

SELECT occupation, salary
FROM parks_and_recreation.employee_salary
GROUP BY occupation, salary 
;

-- ORDER BY --
# ORDER BY ADALAH BERFUNGSI UNTUK MEMFILTER HASIL YANG DIPILIH BAIK A-Z ATAU Z-A 

SELECT *
FROM parks_and_recreation.employee_demographics
-- ORDER BY first_name ASC -- HASILNYA INI MEMFILTER SORT DARI A - Z (DEFAULT) ATAU BISA JUGA DITAMBAHKAN ASC (TANDA SORT BY ASCENDING)
ORDER BY first_name DESC -- HASILNYA INI MEMFILTER SORT DARI Z  - A
;

# CONTOH LAIN
SELECT *
FROM parks_and_recreation.employee_demographics
ORDER BY age, gender
;
# USAHA UNTUK SORTIR DENGAN ORDER BY KOLOM DILAKUKAN SECARA TERSUSUN DARI POSISI KIRI KE KANAN
# JIKA TERBALIK BISA JADI SORT JADI TIDAK BERGUNA
# JIKA KITA TIDAK INGIN MENGGUNAKAN NAMA KOLOM, BISA JUGA MENGGUNAKAN POSISI KOLOM (NOMOR KOLOM) (TDK DIREKOMENDASIKAN) KARNA LEBIH UTAMA BASE PRACTICE MENGGUNAKAN NAMA KOLOM
